- type: entity
  parent: SquadBase
  id: AU14SquadGROM
  name: GROM
  components:
  - type: SquadTeam
    color: "#edae72"
    blacklistedSquadArmor:
    - Helmet
    - Goggles
    - Armor
    - Gloves
    radio: MarineAlpha
    minimapBackground:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: background_spp_alpha
    canSupplyDrop: false
    group: GROM
  - type: Tag
    tags:
    - AU14SquadGROM

- type: entity
  parent: SquadBase
  id: AU14SquadTD
  name: Territorial Defense
  components:
  - type: SquadTeam
    color: "#edae72"
    blacklistedSquadArmor:
    - Helmet
    - Goggles
    - Armor
    - Gloves
    radio: MarineAlpha
    minimapBackground:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: background_spp
    canSupplyDrop: false
    group: TD
  - type: Tag
    tags:
    - AU14SquadTD

- type: entity
  parent: SquadBase
  id: AU14SquadUACG
  name: Colonial Guard
  components:
  - type: SquadTeam
    color: "#edae72"
    blacklistedSquadArmor:
    - Helmet
    - Goggles
    - Armor
    - Gloves
    radio: MarineAlpha
    minimapBackground:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: background_ua
    canSupplyDrop: false
    group: UACG
  - type: Tag
    tags:
    - AU14SquadUACG

- type: entity
  parent: SquadBase
  id: AU14SquadUSArmy
  name: US Army
  components:
  - type: SquadTeam
    color: "#edae72"
    blacklistedSquadArmor:
    - Helmet
    - Goggles
    - Armor
    - Gloves
    radio: MarineAlpha
    minimapBackground:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: background_ua
    canSupplyDrop: false
    group: USArmy
  - type: Tag
    tags:
    - AU14SquadUSArmy

- type: Tag
  id: AU14SquadUACG

- type: Tag
  id: AU14SquadGROM

- type: Tag
  id: AU14SquadTD

- type: Tag
  id: AU14SquadUSArmy