- type: job
  parent: AU14Jobk9handlerBase
  id: AU14JobOPFORk9handler
  name: K9 Handler
  description: K9 Handler
  setPreference: false
  ranks:
    RMCRankStaffSergeant: []
  startingGear: AU14GearopforPlatoonCorpsman
  icon: "AU14JobIconOPFORK9Handler"
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-opfor
  accessGroups:
  - AU14OpforCorpsman
  - AU14OpforSquad
  overwatchSortPriority: -2
  overwatchRoleName: K9 Handler
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - OPFOR
    - type: Marine
      Faction: opfor
    - type: Skills
      preset: AU14SkillPresetPlatoonHospitalCorpsman
    - type: JobPrefix
      prefix: au14-job-prefix-opfork9handler
    - type: TacticalMapIcon
      icon:
        sprite: _RMC14/Interface/map_blips.rsi
        state: synth
  hidden: true

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointOPFORK9Handler
  name: (DO NOT MAP) Spawn Point OPFOR K9 Handler
  components:
  - type: SpawnPoint
    job_id: AU14JobOPFORk9handler
  - type: Sprite
    state: syn_spawn