- type: job
  parent: AU14JobSquadSergeantBase
  id: AU14JobGOVFORSquadSergeantCMBCIU
  name: Team Leader
  description: au14-job-description-govforsquadsergeant
  setPreference: false
  canBeAntag: false
  ranks:
    AU14RankCMBSrDeputy: []
  startingGear: AU14GearGOVFORSquadSergeant
  dummyStartingGear: AU14GearGOVFORSquadSergantDummy
  icon: "AU14JobIconSarge"
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-govfor
  accessGroups:
  - AU14GovforFTL
  overwatchSortPriority: -5
  overwatchRoleName: Squad Sergeant
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillConstruction: 2
        RMCSkillEngineer: 3
        RMCSkillFirearms: 2
        RMCSkillFireman: 1
        RMCSkillJtac: 3
        RMCSkillPolice: 2
    - type: JobPrefix
      prefix: au14-job-prefix-AU14JobGOVFORSquadSergeantCMBCIU
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: synth
    - type: MarineOrders
  hidden: true
