- type: job
  parent: AU14JobPlatCoBase
  id: AU14JobGOVFORPlatCoCMBCIU
  name: Platoon Commander
  description: au14-job-description-govforplatco
  setPreference: false
  canBeAntag: false
  ranks:
    AU14RankCMBMarshal: []
  startingGear: AU14GearGOVFORPlatCo
  icon: "AU14JobIconPlatCo"
  requireAdminNotify: true
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-govforplatco
  accessGroups:
  - AU14GovforCommand
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillCqc: 2
        RMCSkillConstruction: 2
        RMCSkillEndurance: 2
        RMCSkillEngineer: 2
        RMCSkillFirearms: 2
        RMCSkillFireman: 2
        RMCSkillIntel: 2
        RMCSkillJtac: 4
        RMCSkillLeadership: 3
        RMCSkillMedical: 3
        RMCSkillNavigations: 1
        RMCSkillOverwatch: 1
        RMCSkillPolice: 2
        RMCSkillPowerLoader: 2
        RMCSkillSurgery: 1
        RMCSkillVehicles: 1
    - type: JobPrefix
      prefix: au14-job-prefix-AU14JobGOVFORPlatCoCMBCIU
    - type: TacticalMapIcon
      icon:
        sprite: _RMC14/Interface/map_blips.rsi
        state: synth
  hidden: true
