- type: entity
  id: AU14SkillPresetPlatoonRifleman
  name: Rifleman
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
        RMCSkillConstruction: 1
        RMCSkillCqc: 1
        RMCSkillEndurance: 1
        RMCSkillEngineer: 1
        RMCSkillFirearms: 1
        RMCSkillFireman: 2
        RMCSkillVehicles: 1
        RMCSkillJtac: 1

- type: entity
  id: AU14SkillPresetPlatoonRTO
  name: Radio Traffic Operator
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
        RMCSkillConstruction: 1
        RMCSkillCqc: 1
        RMCSkillEndurance: 1
        RMCSkillEngineer: 1
        RMCSkillFirearms: 1
        RMCSkillFireman: 2
        RMCSkillVehicles: 1
        RMCSkillJtac: 4

- type: entity
  id: AU14SkillPresetPlatoonAutomaticRifleman
  name: Automatic Rifleman
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
        RMCSkillConstruction: 1
        RMCSkillCqc: 1
        RMCSkillEndurance: 2
        RMCSkillEngineer: 1
        RMCSkillFirearms: 1
        RMCSkillFireman: 2
        RMCSkillVehicles: 1
        RMCSkillSmartGun: 1
        RMCSkillJtac: 1

- type: entity
  id: AU14SkillPresetPlatoonHospitalCorpsman
  name: Hospital Corpsman
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
        RMCSkillConstruction: 1
        RMCSkillCqc: 1
        RMCSkillEndurance: 1
        RMCSkillEngineer: 1
        RMCSkillFirearms: 1
        RMCSkillFireman: 3
        RMCSkillVehicles: 1
        RMCSkillMedical: 2
        RMCSkillSurgery: 1
        RMCSkillJtac: 1

- type: entity
  id: AU14SkillPresetPlatoonCombatTechnician
  name: Combat Technician
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
        RMCSkillConstruction: 4
        RMCSkillCqc: 1
        RMCSkillEndurance: 1
        RMCSkillEngineer: 4
        RMCSkillFirearms: 1
        RMCSkillFireman: 2
        RMCSkillVehicles: 1
        RMCSkillJtac: 2
        RMCSkillPowerLoader: 2

- type: entity
  id: AU14SkillPresetPlatoonSergeant
  name: Sergeant
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
        RMCSkillConstruction: 1
        RMCSkillCqc: 1
        RMCSkillEndurance: 2
        RMCSkillEngineer: 1
        RMCSkillFirearms: 1
        RMCSkillFireman: 2
        RMCSkillVehicles: 1
        RMCSkillLeadership: 2
        RMCSkillJtac: 3

- type: entity
  id: AU14SkillPresetPlatoonSeniorSergeant
  name: Senior Sergeant
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
        RMCSkillConstruction: 2
        RMCSkillCqc: 2
        RMCSkillEndurance: 3
        RMCSkillEngineer: 2
        RMCSkillFirearms: 2 #gunny has more time on the range than the entire platoon, rumour is he rucks 20 miles a day just to get a weyburger
        RMCSkillFireman: 2
        RMCSkillVehicles: 1
        RMCSkillOverwatch: 1
        RMCSkillPilot: 1
        RMCSkillLeadership: 3
        RMCSkillIntel: 1
        RMCSkillPowerLoader: 1
        RMCSkillMedical: 1
        RMCSkillSurgery: 1
        RMCSkillNavigations: 1
        RMCSkillPolice: 1
        RMCSkillJtac: 4

- type: entity
  id: AU14SkillPresetPlatoonJuniorOfficer
  name: Junior Officer
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
        RMCSkillConstruction: 2
        RMCSkillCqc: 1
        RMCSkillEndurance: 1
        RMCSkillEngineer: 2
        RMCSkillFirearms: 1
        RMCSkillFireman: 1 #fat second el-tee
        RMCSkillVehicles: 1
        RMCSkillOverwatch: 1
        RMCSkillPilot: 1
        RMCSkillLeadership: 3
        RMCSkillIntel: 2
        RMCSkillPowerLoader: 1
        RMCSkillMedical: 1
        RMCSkillSurgery: 1
        RMCSkillNavigations: 1
        RMCSkillPolice: 2
        RMCSkillJtac: 3

- type: entity
  id: AU14SkillPresetPlatoonCommander
  name: Commander
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
        RMCSkillConstruction: 3
        RMCSkillCqc: 2
        RMCSkillEndurance: 3
        RMCSkillEngineer: 3
        RMCSkillFirearms: 2
        RMCSkillFireman: 2
        RMCSkillVehicles: 1
        RMCSkillOverwatch: 1
        RMCSkillPilot: 1
        RMCSkillLeadership: 4
        RMCSkillIntel: 2
        RMCSkillPowerLoader: 1
        RMCSkillMedical: 1
        RMCSkillSurgery: 1
        RMCSkillNavigations: 1
        RMCSkillPolice: 2
        RMCSkillJtac: 3

- type: entity
  id: AU14SkillPresetPlatoonAdvisor
  name: Advisor
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
        RMCSkillConstruction: 4
        RMCSkillCqc: 4
        RMCSkillEndurance: 4
        RMCSkillEngineer: 4
        RMCSkillFirearms: 2
        RMCSkillFireman: 3
        RMCSkillVehicles: 2
        RMCSkillOverwatch: 1
        RMCSkillPilot: 2
        RMCSkillLeadership: 2
        RMCSkillIntel: 2
        RMCSkillPowerLoader: 2
        RMCSkillMedical: 4
        RMCSkillSurgery: 4
        RMCSkillNavigations: 1
        RMCSkillPolice: 2
        RMCSkillJtac: 4

- type: entity
  id: AU14SkillPresetPlatoonDP
  name: Dropship Pilot
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
        RMCSkillConstruction: 2
        RMCSkillCqc: 1
        RMCSkillEndurance: 1
        RMCSkillEngineer: 2
        RMCSkillFirearms: 1
        RMCSkillFireman: 2
        RMCSkillVehicles: 2
        RMCSkillOverwatch: 1
        RMCSkillPilot: 2
        RMCSkillLeadership: 3
        RMCSkillIntel: 2
        RMCSkillPowerLoader: 2
        RMCSkillMedical: 2
        RMCSkillSurgery: 1
        RMCSkillNavigations: 1
        RMCSkillPolice: 1
        RMCSkillJtac: 3

- type: entity
  id: AU14SkillPresetPlatoonDCC
  name: Dropship Crew Chief
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
        RMCSkillConstruction: 1
        RMCSkillCqc: 1
        RMCSkillEndurance: 1
        RMCSkillEngineer: 1
        RMCSkillFirearms: 1
        RMCSkillFireman: 2
        RMCSkillVehicles: 2
        RMCSkillPilot: 2
        RMCSkillIntel: 1
        RMCSkillPowerLoader: 2
        RMCSkillMedical: 2
        RMCSkillSurgery: 1
        RMCSkillNavigations: 1
        RMCSkillPolice: 1
        RMCSkillJtac: 4

- type: entity
  id: AU14SkillPresetPlatoonAuxiliarySupportSynth
  name: Auxiliary Support Synth
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
        RMCSkillCqc: 5
        RMCSkillEndurance: 1
        RMCSkillEngineer: 4
        RMCSkillConstruction: 3
        RMCSkillFirearms: 2
        RMCSkillOverwatch: 1
        RMCSkillMedical: 4
        RMCSkillSurgery: 3
        RMCSkillResearch: 1
        RMCSkillMeleeWeapons: 2
        RMCSkillPilot: 2
        RMCSkillPolice: 2
        RMCSkillFireman: 5
        RMCSkillPowerLoader: 2
        RMCSkillVehicles: 2
        RMCSkillJtac: 3
        RMCSkillIntel: 2
        RMCSkillDomestics: 2
        RMCSkillNavigations: 1

- type: entity
  id: AU14SkillPresetMilitaryDoctor
  name: Military Doctor
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillFirearms: 1
      RMCSkillFireman: 2
      RMCSkillVehicles: 1
      RMCSkillOverwatch: 1
      RMCSkillLeadership: 1
      RMCSkillIntel: 1
      RMCSkillMedical: 4
      RMCSkillSurgery: 4
      RMCSkillPolice: 1
