- type: job
  parent: AU14JobAuxSupportSynthBase
  id: AU14JobGOVFORAuxSupportSynth
  name: au14-job-name-govforauxsupportsynth
  description: au14-job-description-govforauxsupportsynth
  setPreference: true
  canBeAntag: false
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 7200 # 2 hours
  - !type:TraitsRequirement
    inverted: true
    traits:
    - SocialAnxietyHeavy
    - FrontalLisp
    - NonResuscitable
    - Epilepsy
  ranks:
    RMCRankChiefWarrantOfficer5:
    - !type:RoleTimeRequirement
      role: AU14JobFORECONSynth
      time: 252000 #70 hours
    RMCRankChiefWarrantOfficer4:
    - !type:RoleTimeRequirement
      role: AU14JobFORECONSynth
      time: 180000 #50 hours
    RMCRankChiefWarrantOfficer3:
    - !type:RoleTimeRequirement
      role: AU14JobFORECONSynth
      time: 36000 #10 hours
    RMCRankChiefWarrantOfficer:
    - !type:RoleTimeRequirement
      role: AU14JobFORECONSynth
      time: 18000 #5 hours
    RMCRankWarrantOfficer: []
  startingGear: AU14GearGOVFORAuxSupportSynth
  dummyStartingGear: AU14GearGOVFORAuxSupportSynthDummy
  icon: "AU14JobIconGovSynth"
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-govforplatco
  accessGroups:
  - AU14GovforCommand
  - CMCargoTech
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - GOVFOR
    - type: Marine
      Faction: govfor
    - type: Skills
      preset: AU14SkillPresetPlatoonAuxiliarySupportSynth
    - type: JobPrefix
      prefix: au14-job-prefix-govforauxsupportsynth
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: synth
    - type: MeleeWeapon
      soundHit:
        path: /Audio/_RMC14/Weapons/synthpunch1.ogg
        params:
          variation: 0.15
          volume: -1
      angle: 30
      animation: WeaponArcFist
      attackRate: 1
      damage:
        types:
          Blunt: 35
    - type: Synth
  hidden: false

- type: startingGear
  id: AU14GearGOVFORAuxSupportSynth
  equipment:
    id: AU14IDCardGOVFORAuxSupportSynth
    ears: RMCM5CameraGear
    ears2: AU14HeadsetSectionLeader
    gloves: CMHandsInsulated
    shoes: CMBootsBlackFilled
    jumpsuit: AU14CivilianBoilerSuitDarkBlueSynth
    belt: CMUBeltMedicBagSupportSynth
    head: AU14CivBallCapBlack
    back: AU14SmartpackBlackFilled
    pocket1: AU14PouchToolsFilledSupportSynthetic
    pocket2: AU14PouchPoliceEquipmentSupportSynth
    outerClothing: AU14CMDefibrillator

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointGOVFORAuxSupportSynth
  name: Spawn Point GOVFOR Support Synth
  components:
  - type: SpawnPoint
    job_id: AU14JobGOVFORAuxSupportSynth
  - type: Sprite
    state: syn_spawn

- type: startingGear
  id: AU14GearGOVFORAuxSupportSynthDummy
  equipment:
    gloves: CMHandsInsulated
    shoes: CMBootsBlackFilled
    jumpsuit: AU14CivilianBoilerSuitDarkBlueSynth
    belt: CMUBeltMedicBagSupportSynth
    head: AU14CivBallCapBlack
    back: AU14SmartpackBlackFilled
