- type: job
  parent: AU14JobDSPilotBase
  id: AU14JobGOVFORDSPilot
  name: au14-job-name-govfordspilot
  description: au14-job-description-govfordspilot
  setPreference: true
  canBeAntag: false
  requirements:
  - !type:AgeRequirement
    requiredAge: 25
  - !type:TraitsRequirement
    inverted: true
    traits:
    - SocialAnxietyHeavy
    - FrontalLisp
    - NonResuscitable
    - Epilepsy
  ranks:
    RMCRankCaptain:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORDSPilot
      time: 432000 # 120 hours
    RMCRankFirstLT:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORDSPilot
      time: 216000 # 60 hours
    RMCRankSecondLT: []
  startingGear: AU14GearGOVFORDSPilot
  dummyStartingGear: AU14GearGOVFORDSPilotDummy
  icon: "AU14JobIconPilotOfficer"
  requireAdminNotify: true
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-govfor
  accessGroups:
  - AU14GovforPilot
  - AU14GovforCorpsman
  - AU14GovforSquad
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - GOVFOR
    - type: Marine
      Faction: govfor
    - type: Skills
      preset: AU14SkillPresetPlatoonDP
    - type: JobPrefix
      prefix: au14-job-prefix-govfordspilot
    - type: TacticalMapIcon
      icon:
        sprite: _RMC14/Interface/map_blips.rsi
        state: synth
  hidden: true

- type: startingGear
  id: AU14GearGOVFORDSPilot
  equipment:
    id: AU14IDCardGOVFORDSPilot
    ears: AU14HeadsetSectionLeader
- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointGOVFORDSPilot
  name: Spawn Point GOVFOR Dropship Pilot
  components:
  - type: SpawnPoint
    job_id: AU14JobGOVFORDSPilot
  - type: Sprite
    state: syn_spawn

- type: startingGear
  id: AU14GearGOVFORDSPilotDummy
  equipment:
    outerClothing: AU14USASFICPS2
    shoes: CMBootsBrown
    mask: AU14MaskUSASFPilotOxygen
    head: AU14USASFAirCrewHelmet
    jumpsuit: AU14USASFPilotJumpsuit
    ears: AU14HeadsetSectionLeader
