- type: job
  parent: AU14JobSquadRiflemanBase
  id: AU14JobGOVFORSquadRifleman
  name: au14-job-name-govforsquadrifleman
  description: au14-job-description-govforsquadrifleman
  setPreference: true
  requirements:
  - !type:TraitsRequirement
    inverted: true
    traits:
    - Epilepsy
  ranks:
    RMCRankPrivateFirstClass:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadRifleman
      time: 54000 # 15 hours
    RMCRankPrivate: []
  startingGear: AU14GearGOVFORSquadRifleman
  dummyStartingGear: AU14GearGOVFORRiflemanDummy
  icon: "CMJobIconEmpty"
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-govfor
  accessGroups:
  - AU14GovforSquad
  hasIcon: false
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - GOVFOR
    - type: Marine
      Faction: govfor
    - type: Skills
      preset: AU14SkillPresetPlatoonRifleman
    - type: JobPrefix
      prefix: au14-job-prefix-govforsquadrifleman
    - type: TacticalMapIcon
      icon:
        sprite: _RMC14/Interface/map_blips.rsi
        state: synth
  hidden: true

- type: startingGear
  id: AU14GearGOVFORSquadRifleman
  equipment:
    id: AU14IDCardSquadRifleman
    ears: AU14HeadsetSectionMarine
- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointGOVFORSquadRifleman
  name: Spawn Point GOVFOR Squad Rifleman
  components:
  - type: SpawnPoint
    job_id: AU14JobGOVFORSquadRifleman
  - type: Sprite
    state: syn_spawn

- type: startingGear
  id: AU14GearGOVFORRiflemanDummy
  equipment:
    outerClothing: AU14ArmorM3JungleThree
    shoes: AU14BootsJungle
    head: AU14JungleM10Helmet
    jumpsuit: AU14JungleFatigues
    ears: AU14HeadsetSectionMarine
