- type: job
  parent: AU14JobRadioTelephoneOperatorBase
  id: AU14JobGOVFORRadioTelephoneOperator
  name: au14-job-name-radiotelephoneoperator
  description: au14-job-description-radiotelephoneooerator
  setPreference: true
  requirements:
  - !type:TraitsRequirement
    inverted: true
    traits:
    - Epilepsy
    - NonResuscitable
  ranks:
    RMCRankCorporal:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORRadioTelephoneOperator
      time: 216000 # 60 hours
    RMCRankLanceCorporal:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORRadioTelephoneOperator
      time: 108000 # 30 hours
    RMCRankPrivateFirstClass: []
  startingGear: AU14GearGOVFORRadioTelephoneOperator
  dummyStartingGear: AU14GearGOVFORRadioTelephoneOperatorDummy
  icon: "AU14JobIconRTO"
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-govfor
  accessGroups:
  - AU14GovforFTL
  overwatchSortPriority: -5
  overwatchRoleName: Radio Telephone Operator
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - GOVFOR
    - type: Marine
      Faction: govfor
    - type: Skills
      preset: AU14SkillPresetPlatoonRTO
    - type: JobPrefix
      prefix: au14-job-prefix-radiotelephoneoperator
    - type: TacticalMapIcon
      icon:
        sprite: _RMC14/Interface/map_blips.rsi
        state: tl
    - type: MarineOrders
  hidden: true

- type: startingGear
  id: AU14GearGOVFORRadioTelephoneOperator
  equipment:
    id: AU14JobIDCardGOVFORRadioTelephoneOperator
    ears: AU14HeadsetSectionMarine
- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointGOVFORRadioTelephoneOperator
  name: Spawn Point GOVFOR Radio Telephone Operator
  components:
  - type: SpawnPoint
    job_id: AU14JobGOVFORRadioTelephoneOperator
  - type: Sprite
    state: syn_spawn

- type: startingGear
  id: AU14GearGOVFORRadioTelephoneOperatorDummy
  equipment:
    outerClothing: AU14ArmorM3JungleOne
    shoes: CMBootsBrown
    head: AU14JungleBoonieHat
    jumpsuit: AU14JungleFatigues
    ears: AU14HeadsetSectionMarine
