- type: job
  parent: AU14JobSectionSergeantBase
  id: AU14JobGOVFORSectionSergeant
  name: au14-job-name-govforSSG
  description: au14-job-description-govforSSG
  setPreference: true
  requirements:
  - !type:TraitsRequirement
    inverted: true
    traits:
    - SocialAnxietyHeavy
    - FrontalLisp
    - NonResuscitable
    - Epilepsy
  ranks:
    RMCRankMasterSergeant:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSectionSergeant
      time: 432000 # 120 hours
    RMCRankGunnerySergeant:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSectionSergeant
      time: 216000 # 60 hours
    RMCRankStaffSergeant: []
  startingGear: AU14GearGOVFORSectionSergeant
  dummyStartingGear: AU14GearGOVFORPlatoonSergantDummy
  icon: "AU14JobIconPlatoonSarge"
  requireAdminNotify: true
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-govfor
  accessGroups:
  - AU14GovforCommand
  overwatchSortPriority: -6
  overwatchShowName: true
  overwatchRoleName: Platoon Sergeant
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - GOVFOR
    - type: Marine
      Faction: govfor
    - type: Skills
      preset: AU14SkillPresetPlatoonSeniorSergeant
    - type: JobPrefix
      prefix: au14-job-prefix-govforSSG
    - type: TacticalMapIcon
      icon:
        sprite: _RMC14/Interface/map_blips.rsi
        state: synth
    - type: MarineOrders
  hidden: true

- type: startingGear
  id: AU14GearGOVFORSectionSergeant
  equipment:
    id: AU14IDCardSecSergeant
    ears: AU14HeadsetSectionMarine
- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointGOVFORSectionSergeant
  name: Spawn Point GOVFOR Section Sergeant
  components:
  - type: SpawnPoint
    job_id: AU14JobGOVFORSectionSergeant
  - type: Sprite
    state: syn_spawn

- type: startingGear
  id: AU14GearGOVFORPlatoonSergantDummy
  equipment:
    outerClothing: AU14ArmorM3JungleTwo
    shoes: CMBootsBrown
    head: AU14JunglePatrolCap
    jumpsuit: AU14JungleFatigues
    ears: AU14HeadsetSectionMarine
