- type: job
  parent: AU14JobSquadCombatTechBase
  id: AU14JobGOVFORSquadCombatTech
  name: au14-job-name-govforsquadcombattech
  description: au14-job-description-govforsquadcombattech
  setPreference: true
  requirements:
  - !type:TraitsRequirement
    inverted: true
    traits:
    - Epilepsy
    - NonResuscitable
  ranks:
    RMCRankCorporal:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadAutomaticRifleman
      time: 216000 # 60 hours
    RMCRankLanceCorporal:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadAutomaticRifleman
      time: 108000 # 30 hours
    RMCRankPrivateFirstClass:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadAutomaticRifleman
      time: 54000 # 15 hours
    RMCRankPrivate: []
  startingGear: AU14GearGOVFORSquadCombatTech
  dummyStartingGear: AU14GearGOVFORCTDummy
  icon: "AU14JobIconGovCT"
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-govfor
  accessGroups:
  - AU14GovforEngineer
  hasIcon: true
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - GOVFOR
    - type: Marine
      Faction: govfor
    - type: Skills
      preset: AU14SkillPresetPlatoonCombatTechnician
    - type: JobPrefix
      prefix: au14-job-prefix-govforsquadcombattech
    - type: TacticalMapIcon
      icon:
        sprite: _RMC14/Interface/map_blips.rsi
        state: engi
    - type: CMVendorUser
      id: AU14JobGOVFORSquadCombatTech
      points: 50
  hidden: true

- type: startingGear
  id: AU14GearGOVFORSquadCombatTech
  equipment:
    id: AU14IDCardSquadCombatTech
    ears: AU14HeadsetSectionMarine

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointGOVFORSquadCombatTech
  name: Spawn Point GOVFOR Comtech
  components:
  - type: SpawnPoint
    job_id: AU14JobGOVFORSquadCombatTech
  - type: Sprite
    state: syn_spawn

- type: startingGear
  id: AU14GearGOVFORCTDummy
  equipment:
    outerClothing: AU14ArmorM3JungleThree
    shoes: AU14BootsJungle
    head: AU14JungleM10Helmet
    jumpsuit: AU14JungleFatigues
    ears: AU14HeadsetSectionMarine
