- type: job
  parent: AU14JobDCCBase
  id: AU14JobGOVFORDCC
  name: au14-job-name-govfordcc
  description: au14-job-description-govfordcc
  setPreference: true
  canBeAntag: false
  requirements:
  - !type:TraitsRequirement
    inverted: true
    traits:
    - Epilepsy
    - NonResuscitable
  ranks:
    AU14RankUSASFCMSgt:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORDCC
      time: 432000 # 120 hours
    AU14RankUSASFSMSgt:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORDCC
      time: 216000 # 60 hours
    AU14RankUSASFMasterSergeant:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORDCC
      time: 43200 # 12 hours
    AU14RankUSASFTechnicalSergeant: []
  startingGear: AU14GearGOVFORDCC
  dummyStartingGear: AU14GearGOVFORDCCDummy
  icon: "AU14JobIconDCC"
  requireAdminNotify: true
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-govfor
  accessGroups:
  - AU14GovforPilot
  - AU14GovforCorpsman
  - AU14GovforSquad
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - GOVFOR
    - type: Marine
      Faction: govfor
    - type: Skills
      preset: AU14SkillPresetPlatoonDCC
    - type: JobPrefix
      prefix: au14-job-prefix-govfordcc
    - type: TacticalMapIcon
      icon:
        sprite: _RMC14/Interface/map_blips.rsi
        state: synth
  hidden: true

- type: startingGear
  id: AU14GearGOVFORDCC
  equipment:
    id: AU14IDCardGOVFORDCC
    ears: AU14HeadsetSectionLeader
- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointGOVFORDCC
  name: Spawn Point GOVFOR Dropship Crew Chief
  components:
  - type: SpawnPoint
    job_id: AU14JobGOVFORDCC
  - type: Sprite
    state: syn_spawn

- type: startingGear
  id: AU14GearGOVFORDCCDummy
  equipment:
    outerClothing: AU14USASFICPS2
    shoes: CMBootsBrown
    head: AU14USASFAirCrewHelmet
    jumpsuit: AU14USASFPilotJumpsuit
    ears: AU14HeadsetSectionMarine
