- type: job
  parent: AU14JobSquadSergeantBase
  id: AU14JobGOVFORSquadSergeant
  name: au14-job-name-govforsquadsergeant
  description: au14-job-description-govforsquadsergeant
  setPreference: true
  canBeAntag: false
  requirements:
  - !type:TraitsRequirement
    inverted: true
    traits:
    - SocialAnxietyHeavy
    - FrontalLisp
    - NonResuscitable
    - Epilepsy
  ranks:
    RMCRankSergeant: []
  startingGear: AU14GearGOVFORSquadSergeant
  dummyStartingGear: AU14GearGOVFORSquadSergantDummy
  icon: "AU14JobIconSarge"
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-govfor
  accessGroups:
  - AU14GovforFTL
  overwatchSortPriority: -4
  overwatchRoleName: Squad Leader
  overwatchShowName: true
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - GOVFOR
    - type: Marine
      Faction: govfor
    - type: Skills
      preset: AU14SkillPresetPlatoonSergeant
    - type: JobPrefix
      prefix: au14-job-prefix-govforsquadsergeant
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: leader
    - type: MarineOrders
  hidden: false

- type: startingGear
  id: AU14GearGOVFORSquadSergeant
  equipment:
    id: AU14IDCardSquadSergeant
    ears: AU14HeadsetSectionLeader
- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointGOVFORSquadSergeant
  name: Spawn Point GOVFOR Squad Sergeant
  components:
  - type: SpawnPoint
    job_id: AU14JobGOVFORSquadSergeant
  - type: Sprite
    state: syn_spawn

- type: startingGear
  id: AU14GearGOVFORSquadSergantDummy
  equipment:
    outerClothing: AU14ArmorM3JungleOne
    shoes: CMBootsBrown
    head: AU14JungleBoonieHat
    jumpsuit: AU14JungleFatigues
    earss: AU14HeadsetSectionLeader
