
- type: job
  parent: CMJobBase
  id: CMCommandingOfficer
  name: cm-job-name-commanding-officer
  description: cm-job-description-commanding-officer
  setPreference: false
  playTimeTracker: CMJobCommandingOfficer
  requirements: []
  ranks:
    RMCRankColonel:
    - !type:RoleTimeRequirement
      role: CMJobCommandingOfficer
      time: 630000 # 175 hours
    RMCRankLieutenantColonel:
    - !type:RoleTimeRequirement
      role: CMJobCommandingOfficer
      time: 252000 # 70 hours
    RMCRankMajor: []
  weight: 10
  startingGear: CMGearCommandingOfficer
  icon: "CMJobIconCommandingOfficer"
  requireAdminNotify: true
  joinNotifyCrew: true
  marineAuthorityLevel: 15
  supervisors: cm-job-supervisors-marine-high-command
  whitelisted: true
  accessGroups:
  - ShipMasterAccess
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      preset: RMCSkillPresetCommander
    - type: MarineOrders
    - type: CMVendorUser
      id: CMCommandingOfficer
      points: 120
    - type: RMCPointing
    - type: JobPrefix
      prefix: cm-job-prefix-commanding-officer
    - type: CommendationGiver
    - type: ViewIntelObjectives
    - type: CommandAccent
    - type: InnateCommandSpeech
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: dcc
      background:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: background_command
    - type: RMCTrackable

- type: startingGear
  id: CMGearCommandingOfficer
  equipment:
    jumpsuit: CMJumpsuitBO
    shoes: CMShoesLaceupCommander
    head: CMHeadBeretCO
    outerClothing: RMCCoatService
    ears: CMHeadsetSeniorCommand
    pocket1: RMCPouchCommand
    pocket2: RMCPouchGeneralLarge

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointCommandingOfficer
  name: commanding officer spawn point
  components:
  - type: SpawnPoint
    job_id: CMCommandingOfficer
  - type: Sprite
    state: co_spawn

- type: playTimeTracker
  id: CMJobCommandingOfficer
  isHumanoid: true

- type: entity
  parent: CMGuidebookRole
  id: RMCGuidebookRoleCO
  name: The Commanding Officer
  description: The Commanding Officer.
  categories: [ HideSpawnMenu ]
  components:
  - type: Sprite
    state: commanding_officer
