- type: job
  parent: CMJobBase
  id: AU14JobadvisorBase
  name: au14-job-name-govforadvisor
  description: au14-job-description-govforadvisor
  playTimeTracker: AU14JobGOVFORadvisor
  basePlaytimeTracker: true
  hidden: true

- type: playTimeTracker
  id: AU14JobGOVFORadvisor
  isHumanoid: true
