- type: job
  parent: CMJobBase
  id: AU14JobDCCBase
  name: au14-job-name-govfordcc
  description: au14-job-description-govfordcc
  playTimeTracker: AU14JobGOVFORDCC
  basePlaytimeTracker: true
  hidden: true

- type: playTimeTracker
  id: AU14JobGOVFORDCC
  isHumanoid: true
