- type: job
  parent: CMJobBase
  id: AU14JobMilitaryDoctorBase
  name: au14-job-name-govforsquadsergeant
  description: au14-job-description-govforsquadsergeant
  playTimeTracker: AU14JobGOVFORMilitaryDoctor
  basePlaytimeTracker: true
  hidden: true