- type: job
  parent: CMJobBase
  id: AU14JobPlatOpBase
  name: au14-job-name-govforplatop
  description: au14-job-description-govforplatop
  playTimeTracker: AU14JobGOVFORPlatOp
  basePlaytimeTracker: true
  hidden: true

- type: playTimeTracker
  id: AU14JobGOVFORPlatOp
  isHumanoid: true
