- type: job
  parent: CMJobBase
  id: AU14JobRadioTelephoneOperatorBase
  name: au14-job-name-radiotelephoneoperator
  description: au14-job-description-radiotelephoneooerator
  playTimeTracker: AU14JobGOVFORRadioTelephoneOperator
  basePlaytimeTracker: true
  hidden: true

- type: playTimeTracker
  id: AU14JobGOVFORRadioTelephoneOperator
  isHumanoid: true