- type: job
  parent: CMJobBase
  id: AU14JobSquadSergeantBase
  name: au14-job-name-govforsquadsergeant
  description: au14-job-description-govforsquadsergeant
  playTimeTracker: AU14JobGOVFORSquadSergeant
  basePlaytimeTracker: true
  hidden: true

- type: playTimeTracker
  id: AU14JobGOVFORSquadSergeant
  isHumanoid: true