- type: job
  parent: CMJobBase
  id: AU14JobSquadRiflemanBase
  name: au14-job-name-govforsquadrifleman
  description: au14-job-description-govforsquadrifleman
  playTimeTracker: AU14JobGOVFORSquadRifleman
  basePlaytimeTracker: true
  hidden: true

- type: playTimeTracker
  id: AU14JobGOVFORSquadRifleman
  isHumanoid: true