- type: rank
  id: AU14RankCMBProbDeputy
  name: Probationary Deputy
  prefix: Prob. Dep.

- type: rank
  id: AU14RankCMBDeputy
  name: Deputy
  prefix: Dep.

- type: rank
  id: AU14RankCMBSrDeputy
  name: Senior Deputy
  prefix: Sr. Dep.

- type: rank
  id: AU14RankCMBChiefDeputy
  name: Chief Deputy
  prefix: Chf. Dep.

- type: rank
  id: AU14RankCMBMarshal
  name: CMB Marshal
  prefix: Mrshl.

- type: rank
  id: AU14RankColonyAdministrator
  name: Administrator
  prefix: Admin.

- type: rank
  id: AU14RankColonySeniorAdministrator
  name: Senior Administrator
  prefix: Sr. Admin.

- type: rank
  id: AU14RankCWPSRangerTrainee
  name: Probationary Ranger
  prefix: Prob. Ranger

- type: rank
  id: AU14RankCWPSRanger
  name: Ranger
  prefix: Ranger

- type: rank
  id: AU14RankCWPSSeniorRanger
  name: Senior Ranger
  prefix: Sr. Ranger

- type: rank
  id: AU14RankNSPAConstable
  name: Constable
  prefix: Constable

- type: rank
  id: AU14RankNSPASeniorConstable
  name: Senior Constable
  prefix: Sr. Constable

- type: rank
  id: AU14RankNSPAInspector
  name: Inspector
  prefix: Insp.
