# enlisted
- type: rank
  id: UPP_Private
  name: Private
  prefix: Pvt.
  paygrade: E1

- type: rank
  id: UPP_Gefreiter
  name: Gefreiter
  prefix: Gefr.
  paygrade: E2

- type: rank
  id: UPP_SeniorGefreiter
  name: Senior Gefreiter
  prefix: SnGefr.
  paygrade: E3

- type: rank
  id: UPP_Corporal
  name: Corporal
  prefix: Corp.
  paygrade: E3

- type: rank
  id: UPP_Plutonowy
  name: Plutonowy
  prefix: Plut.
  paygrade: E4

- type: rank
  id: UPP_Sergeant
  name: Sergeant
  prefix: Sgt.
  paygrade: E5

- type: rank
  id: UPP_StaffSergeant
  name: Staff Sergeant
  prefix: SSgt.
  paygrade: E6

- type: rank
  id: UPP_Chotar
  name: Chotar
  prefix: Chot.
  paygrade: E7

- type: rank
  id: UPP_FirstSergeant
  name: First Sergeant
  prefix: 1stSgt.
  paygrade: E8

#  warrant Officers
- type: rank
  id: UPP_WarrantOfficer
  name: Warrant Officer
  prefix: WO.
  paygrade: W1

- type: rank
  id: UPP_SeniorWarrantOfficer
  name: Senior Warrant Officer
  prefix: SnWO.
  paygrade: W2

# officers
- type: rank
  id: UPP_JuniorLieutenant
  name: Junior Lieutenant
  prefix: JnLt.
  paygrade: O1

- type: rank
  id: UPP_Lieutenant
  name: Lieutenant
  prefix: Lt.
  paygrade: O1

- type: rank
  id: UPP_SeniorLieutenant
  name: Senior Lieutenant
  prefix: SnLt.
  paygrade: O2

- type: rank
  id: UPP_Captain
  name: Captain
  prefix: Capt.
  paygrade: O3


#field officers
- type: rank
  id: UPP_Major
  name: Major
  prefix: Maj.
  paygrade: O4

- type: rank
  id: UPP_LieutenantColonel
  name: Lieutenant Colonel
  prefix: Lt Col.
  paygrade: O5

- type: rank
  id: UPP_Colonel
  name: Colonel
  prefix: Col.
  paygrade: O6

# Generals
- type: rank
  id: UPP_BrigadierGeneral
  name: Brigadier-General
  prefix: Brig-Gen.
  paygrade: O7

- type: rank
  id: UPP_DivisionalGeneral
  name: Divisional General
  prefix: Div-Gen.
  paygrade: O8

- type: rank
  id: UPP_GeneralOfTheBranch
  name: General of the branch
  prefix: Gen-Br.
  paygrade: O9

- type: rank
  id: UPP_Marshal
  name: Marshal
  prefix: Marsh.
  paygrade: O10

- type: rank
  id: UPP_ChairmanMilitaryCouncil
  name: Chairman of Military Council
  prefix: CMC
  paygrade: O10

- type: rank
  id: UPP_Commissar
  name: Commissar
  prefix: Comrade