# enlisted
- type: rank
  id: USArmy_Private1
  name: Private
  prefix: Pv1.
  paygrade: E1

- type: rank
  id: USArmy_Private2
  name: Private
  prefix: Pv2.
  paygrade: E2

- type: rank
  id: USArmy_PFC
  name: Private First Class
  prefix: PFC.
  paygrade: E3

- type: rank
  id: USArmy_Specialist
  name: Specialist
  prefix: Spc.
  paygrade: E4

- type: rank
  id: USArmy_Corporal
  name: Corporal
  prefix: Cpl.
  paygrade: E4

- type: rank
  id: USArmy_Sergeant
  name: Sergeant
  prefix: Sgt.
  paygrade: E5

- type: rank
  id: USArmy_StaffSergeant
  name: Staff Sergeant
  prefix: SSgt.
  paygrade: E6

- type: rank
  id: USArmy_SergeantFirstClass
  name: Sergeant First Class
  prefix: SgtFC.
  paygrade: E7

- type: rank
  id: USArmy_MasterSergeant
  name: Master Sergeant
  prefix: MSgt.
  paygrade: E8

- type: rank
  id: USArmy_FirstSergeant
  name: First Sergeant
  prefix: 1stSgt.
  paygrade: E8

- type: rank
  id: USArmy_SergeantMajor
  name: Sergeant Major
  prefix: SgtMaj.
  paygrade: E9

- type: rank
  id: USArmy_CommandSergeantMajor
  name: Command Sergeant Major
  prefix: ComSgtMaj.
  paygrade: E9

- type: rank
  id: USArmy_SEA
  name: Senior Enlisted Advisor
  prefix: SEA.
  paygrade: E9E

- type: rank
  id: USArmy_SergeantMajorArmy
  name: Sergeant Major of the Army
  prefix: SMA.
  paygrade: E9E

- type: rank
  id: USArmy_SEAChairman
  name: Senior Enlisted Advisor to the chairman
  prefix: SEAC.
  paygrade: E9E

#  warrant Officers
- type: rank
  id: USArmy_WarrantOfficer1
  name: Warrant Officer 1
  prefix: WO1.
  paygrade: W1

- type: rank
  id: USArmy_ChiefWarrantOfficer2
  name: Chief Warrant Officer 2
  prefix: CW2.
  paygrade: W2

- type: rank
  id: USArmy_ChiefWarrantOfficer3
  name: Chief Warrant Officer 3
  prefix: CW3.
  paygrade: W3

- type: rank
  id: USArmy_ChiefWarrantOfficer4
  name: Chief Warrant Officer 4
  prefix: CW4.
  paygrade: W4

- type: rank
  id: USArmy_ChiefWarrantOfficer5
  name: Chief Warrant Officer 5
  prefix: CW5.
  paygrade: W5

# officers

- type: rank
  id: USArmy_SecondLieutenant
  name: Second Lieutenant
  prefix: 2Lt.
  paygrade: O1

- type: rank
  id: USArmy_FirstLieutenant
  name: First Lieutenant
  prefix: 1Lt.
  paygrade: O2

- type: rank
  id: USArmy_Captain
  name: Captain
  prefix: Capt.
  paygrade: O3

#field officers
- type: rank
  id: USArmy_Major
  name: Major
  prefix: Maj.
  paygrade: O4

- type: rank
  id: USArmy_LieutenantColonel
  name: Lieutenant Colonel
  prefix: Lt Col.
  paygrade: O5

- type: rank
  id: USArmy_Colonel
  name: Colonel
  prefix: Col.
  paygrade: O6

- type: rank
  id: USArmy_BrigadierGeneral
  name: Brigadier-General
  prefix: Brig-Gen.
  paygrade: O7

- type: rank
  id: USArmy_MajorGeneral
  name: Major-General
  prefix: Maj-Gen.
  paygrade: O7

# Generals
- type: rank
  id: USArmy_GeneralMajor
  name: Major-General
  prefix: GenMaj.
  paygrade: O8

- type: rank
  id: USArmy_LieutenantGeneral
  name: Lieutenant-General
  prefix: Lt Gen.
  paygrade: O9

- type: rank
  id: USArmy_General
  name: General
  prefix: Gen.
  paygrade: O10

- type: rank
  id: USArmy_GeneralArmy
  name: General of the Army
  prefix: Gen. Arm.
  paygrade: O10