- type: job
  parent: AU14JobRadioTelephoneOperatorBase
  id: AU14JobOpforRadioTelephoneOperator
  name: au14-job-name-radiotelephoneoperator
  description: au14-job-description-radiotelephoneoperator
  setPreference: true
  requirements:
  - !type:TraitsRequirement
    inverted: true
    traits:
    - Epilepsy
    - NonResuscitable
  ranks:
    RMCRankCorporal:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORRadioTelephoneOperator
      time: 216000 # 60 hours
    RMCRankLanceCorporal:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORRadioTelephoneOperator
      time: 108000 # 30 hours
    RMCRankPrivateFirstClass: []
  startingGear: AU14GearopforRadioTelephoneOperator
  dummyStartingGear: AU14GearopforRadioTelephoneOperatorDummy
  icon: "AU14JobIconOPFORRTO"
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-opfor
  accessGroups:
  - AU14OpforFTL
  overwatchSortPriority: -5
  overwatchRoleName: Radio Telephone Operator
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - OPFOR
    - type: Marine
      Faction: opfor
    - type: Skills
      preset: AU14SkillPresetPlatoonRTO
    - type: JobPrefix
      prefix: au14-job-prefix-radiotelephoneoperator
    - type: TacticalMapIcon
      icon:
        sprite: _RMC14/Interface/map_blips.rsi
        state: synth
    - type: MarineOrders
  hidden: true

- type: startingGear
  id: AU14GearopforRadioTelephoneOperator
  equipment:
    id: AU14JobIDCardopforRadioTelephoneOperator
    ears: AU14HeadsetSectionOpfor

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointopforRadioTelephoneOperator
  name: Spawn Point opfor Radio Telephone Operator
  components:
  - type: SpawnPoint
    job_id: AU14JobOpforRadioTelephoneOperator
  - type: Sprite
    state: syn_spawn

- type: playTimeTracker
  id: AU14JobOpforRadioTelephoneOperator
  isHumanoid: true

- type: startingGear
  id: AU14GearopforRadioTelephoneOperatorDummy
  equipment:
    outerClothing: AU14ArmorM3JungleOne
    shoes: CMBootsBrown
    head: AU14JungleBoonieHat
    jumpsuit: AU14JungleFatigues
    ears: AU14HeadsetSectionOpfor
