- type: job
  parent: AU14JobSquadCombatTechBase
  id: AU14JobOPFORSquadCombatTech
  name: au14-job-name-opforsquadcombattech
  description: au14-job-description-opforsquadcombattech
  setPreference: true
  overwatchSortPriority: -5
  overwatchRoleName: Combat Technician
  requirements:
  - !type:TraitsRequirement
    inverted: true
    traits:
    - Epilepsy
    - NonResuscitable
  ranks:
    RMCRankCorporal:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadCombatTech
      time: 216000 # 60 hours
    RMCRankLanceCorporal:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadCombatTech
      time: 108000 # 30 hours
    RMCRankPrivateFirstClass:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadCombatTech
      time: 54000 # 15 hours
    RMCRankPrivate: []
  startingGear: AU14GearOPFORSquadCombatTech
  dummyStartingGear: AU14GearOPFORCTDummy
  icon: "AU14JobIconOPFORCT"
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-opfor
  accessGroups:
  - AU14OpforEngineering
  hasIcon: true
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - OPFOR
    - type: Marine
      Faction: opfor
    - type: Skills
      preset: AU14SkillPresetPlatoonCombatTechnician
    - type: JobPrefix
      prefix: au14-job-prefix-opforsquadcombattech
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: engi
    - type: CMVendorUser
      id: AU14JobOPFORSquadCombatTech
      points: 50
  hidden: true

- type: startingGear
  id: AU14GearOPFORSquadCombatTech
  equipment:
    id: AU14IDCardOPFORCT
    ears: AU14HeadsetSectionOpfor

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointOPFORSquadCombatTech
  name: Spawn Point OPFOR Comtech
  components:
  - type: SpawnPoint
    job_id: AU14JobOPFORSquadCombatTech
  - type: Sprite
    state: syn_spawn

- type: startingGear
  id: AU14GearOPFORCTDummy
  equipment:
    outerClothing: AU14ArmorM3JungleThree
    shoes: AU14BootsJungle
    head: AU14JungleM10Helmet
    jumpsuit: AU14JungleFatigues
    ears: AU14HeadsetSectionOpfor
