- type: job
  parent: AU14JobSquadSergeantBase
  id: AU14JobOpforSquadSergeant
  name: au14-job-name-opforsquadsergeant
  description: au14-job-description-opforsquadsergeant
  setPreference: true
  requirements:
  - !type:TraitsRequirement
    inverted: true
    traits:
    - SocialAnxietyHeavy
    - FrontalLisp
    - NonResuscitable
    - Epilepsy
  ranks:
    RMCRankSergeant: []
  startingGear: AU14GearopforSquadSergeant
  dummyStartingGear: AU14GearopforSquadSergantDummy
  icon: "AU14JobIconOPFORSarge"
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-opfor
  accessGroups:
  - AU14OpforFTL
  overwatchSortPriority: -5
  overwatchRoleName: Squad Leader
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - OPFOR
    - type: Marine
      Faction: opfor
    - type: Skills
      preset: AU14SkillPresetPlatoonSergeant
    - type: JobPrefix
      prefix: au14-job-prefix-opforsquadsergeant
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: leader
    - type: MarineOrders
  hidden: false

- type: startingGear
  id: AU14GearopforSquadSergeant
  equipment:
    id: AU14IDCardopforSquadSergeant
    ears: AU14HeadsetSectionLeaderopfor

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointopforSquadSergeant
  name: Spawn Point opfor Squad Sergeant
  components:
  - type: SpawnPoint
    job_id: AU14JobOpforSquadSergeant
  - type: Sprite
    state: syn_spawn

- type: startingGear
  id: AU14GearopforSquadSergantDummy
  equipment:
    outerClothing: AU14ArmorM3JungleOne
    shoes: CMBootsBrown
    head: AU14JungleBoonieHat
    jumpsuit: AU14JungleFatigues
    ears: AU14HeadsetSectionLeaderopfor
