- type: job
  parent: AU14JobDSPilotBase
  id: AU14JobOpforDSPilot
  name: TEST OPFOR DS
  description: au14-job-description-opfordspilot
  setPreference: true
  canBeAntag: false
  requirements:
  - !type:AgeRequirement
    requiredAge: 25
  - !type:TraitsRequirement
    inverted: true
    traits:
    - SocialAnxietyHeavy
    - FrontalLisp
    - NonResuscitable
    - Epilepsy
  ranks:
    RMCRankCaptain:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORDSPilot
      time: 432000 # 120 hours
    RMCRankFirstLT:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORDSPilot
      time: 216000 # 60 hours
    RMCRankSecondLT: []
  startingGear: AU14GearopforDSPilot
  dummyStartingGear: AU14GearopforDSPilotDummy
  icon: "AU14JobIconOPFORPilotOfficer"
  requireAdminNotify: true
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-opfor
  accessGroups:
  - AU14OpforPilot
  - AU14OpforCorpsman
  - AU14OpforSquad
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - OPFOR
    - type: Marine
      Faction: opfor
    - type: Skills
      preset: AU14SkillPresetPlatoonDP
    - type: JobPrefix
      prefix: au14-job-prefix-opfordspilot
    - type: TacticalMapIcon
      icon:
        sprite: _RMC14/Interface/map_blips.rsi
        state: synth
  hidden: true

- type: startingGear
  id: AU14GearopforDSPilot
  equipment:
    id: AU14IDCardopforDSPilot
    ears: AU14HeadsetSectionLeaderopfor

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointopforDSPilot
  name: Spawn Point opfor Dropship Pilot
  components:
  - type: SpawnPoint
    job_id: AU14JobOpforDSPilot
  - type: Sprite
    state: syn_spawn

- type: startingGear
  id: AU14GearopforDSPilotDummy
  equipment:
    outerClothing: AU14USASFICPS2
    shoes: CMBootsBrown
    mask: AU14MaskUSASFPilotOxygen
    head: AU14USASFAirCrewHelmet
    jumpsuit: AU14USASFPilotJumpsuit
    ears: AU14HeadsetSectionLeaderopfor
