- type: job
  parent: AU14JobSquadAutomaticRiflemanBase
  id: AU14JobOpforSquadAutomaticRifleman
  name: au14-job-name-opforsquadautomaticrifleman
  description: au14-job-description-opforsquadautomaticrifleman
  setPreference: true
  requirements:
  - !type:TraitsRequirement
    inverted: true
    traits:
    - Epilepsy
    - NonResuscitable
  ranks:
    RMCRankCorporal:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadAutomaticRifleman
      time: 216000 # 60 hours
    RMCRankLanceCorporal:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadAutomaticRifleman
      time: 108000 # 30 hours
    RMCRankPrivateFirstClass:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadAutomaticRifleman
      time: 54000 # 15 hours
    RMCRankPrivate: []
  startingGear: AU14GearopforSquadAutomaticRifleman
  dummyStartingGear: AU14GearopforAutoRiflemanDummy
  icon: "AU14JobIconOPFORAFN"
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-opfor
  accessGroups:
  - AU14OpforGunner
  overwatchSortPriority: -6
  overwatchRoleName: Automatic Riflemen
  overwatchShowName: true
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
       - OPFOR
    - type: Marine
      Faction: opfor
    - type: Skills
      preset: AU14SkillPresetPlatoonAutomaticRifleman
    - type: SquadArmorWearer
    - type: JobPrefix
      prefix: au14-job-prefix-opforsquadautomaticrifleman
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: smartgunner
  hidden: false

- type: startingGear
  id: AU14GearopforSquadAutomaticRifleman
  equipment:
    id: AU14IDCardopforSquadAutomaticRifleman
    ears: AU14HeadsetSectionOpfor

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointopforSquadAutomaticRifleman
  name: Spawn Point opfor Squad Rifleman
  components:
  - type: SpawnPoint
    job_id: AU14JobOpforSquadAutomaticRifleman
  - type: Sprite
    state: syn_spawn

- type: startingGear
  id: AU14GearopforAutoRiflemanDummy
  equipment:
    outerClothing: AU14ArmorSmartGunJungleCombatHarness
    shoes: AU14BootsJungle
    head: AU14JungleM10Helmet
    jumpsuit: AU14JungleFatigues
    ears: AU14HeadsetSectionOpfor
