- type: job
  parent: CMJobBase
  id: AU14JobOpforSquadRifleman
  name: au14-job-name-opforsquadrifleman
  description: au14-job-description-opforsquadrifleman
  setPreference: true
  playTimeTracker: AU14JobGOVFORSquadRifleman
  requirements:
  - !type:TraitsRequirement
    inverted: true
    traits:
    - Epilepsy
  ranks:
    RMCRankPrivateFirstClass:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadRifleman
      time: 54000 # 15 hours
    RMCRankPrivate: []
  startingGear: AU14GearopforSquadRifleman
  dummyStartingGear: AU14GearopforRiflemanDummy
  icon: "CMJobIconEmpty"
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-opfor
  accessGroups:
  - AU14OpforSquad
  hasIcon: false
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - OPFOR
    - type: Marine
      Faction: opfor
    - type: Skills
      preset: AU14SkillPresetPlatoonRifleman
    - type: JobPrefix
      prefix: au14-job-prefix-opforsquadrifleman
    - type: TacticalMapIcon
      icon:
        sprite: _RMC14/Interface/map_blips.rsi
        state: private
  hidden: false

- type: startingGear
  id: AU14GearopforSquadRifleman
  equipment:
    id: AU14IDCardopforSquadRifleman
    ears: AU14HeadsetSectionOpfor

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointopforSquadRifleman
  name: Spawn Point opfor Squad Rifleman
  components:
  - type: SpawnPoint
    job_id: AU14JobOpforSquadRifleman
  - type: Sprite
    state: syn_spawn

- type: startingGear
  id: AU14GearopforRiflemanDummy
  equipment:
    outerClothing: AU14ArmorM3JungleThree
    shoes: AU14BootsJungle
    head: AU14JungleM10Helmet
    jumpsuit: AU14JungleFatigues
    ears: AU14HeadsetSectionOpfor
