- type: job
  parent: CMJobBase
  id: AU14JobOpforPlatoonCorpsman
  name: au14-job-name-opforplatooncorpsman
  description: au14-job-description-opforplatooncorpsman
  setPreference: true
  playTimeTracker: AU14JobGOVFORPlatoonCorpsman
  requirements:
  - !type:TraitsRequirement
    inverted: true
    traits:
    - Epilepsy
    - NonResuscitable
  ranks:
    RMCRankCorporal:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORPlatoonCorpsman
      time: 4320000 # 20 hours
    RMCRankLanceCorporal: []
  startingGear: AU14GearopforPlatoonCorpsman
  dummyStartingGear: AU14GearopforCorpsmanDummy
  icon: "AU14JobIconOPFORCorpsman"
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-opfor
  accessGroups:
  - AU14OpforCorpsman
  - AU14OpforSquad
  overwatchSortPriority: -2
  overwatchRoleName: Hospital Corpsmen
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      preset: AU14SkillPresetPlatoonHospitalCorpsman
    - type: JobPrefix
      prefix: au14-job-prefix-opforplatooncorpsman
    - type: TacticalMapIcon
      icon:
        sprite: _RMC14/Interface/map_blips.rsi
        state: medic
  hidden: false

- type: startingGear
  id: AU14GearopforPlatoonCorpsman
  equipment:
    id: AU14JobIDCardopforPlatoonCorpsman
    ears: AU14HeadsetSectionOpfor

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointopforPlatoonCorpsman
  name: Spawn Point opfor Squad Sergeant
  components:
  - type: SpawnPoint
    job_id: AU14JobOpforPlatoonCorpsman
  - type: Sprite
    state: syn_spawn

- type: startingGear
  id: AU14GearopforCorpsmanDummy
  equipment:
    outerClothing: AU14ArmorM3JungleOne
    gloves: CMHandsLatex
    shoes: CMBootsBlack
    head: AU14JungleM10CorpsmanHelmet
    jumpsuit: AU14JungleFatigues
    ears: AU14HeadsetSectionOpfor
