- type: job
  parent: AU14JobPlatOpBase
  id: AU14JobOpforPlatOp
  name: au14-job-name-opforplatop
  description: au14-job-description-opforplatop
  setPreference: true
  canBeAntag: false
  requirements:
  - !type:AgeRequirement
    requiredAge: 25
  - !type:TraitsRequirement
    inverted: true
    traits:
    - SocialAnxietyHeavy
    - FrontalLisp
    - NonResuscitable
    - Epilepsy
  ranks:
    RMCRankSecondLT: []
  startingGear: AU14GearopforPlatOp
  dummyStartingGear: AU14GearopforPlatOpDummy
  icon: "AU14JobIconOPFOROpsOfc"
  requireAdminNotify: true
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-opfor
  accessGroups:
  - AU14OpforCommand
  roleWeight: 0.25
  special:

  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - OPFOR
    - type: Marine
      Faction: opfor
    - type: Skills
      preset: AU14SkillPresetPlatoonJuniorOfficer
    - type: JobPrefix
      prefix: au14-job-prefix-opforplatop
    - type: TacticalMapIcon
      icon:
        sprite: _RMC14/Interface/map_blips.rsi
        state: synth
  hidden: true

- type: startingGear
  id: AU14GearopforPlatOp
  equipment:
    id: AU14IDCardopforPlatOp
    ears: AU14HeadsetSectionLeaderopfor

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointopforPlatOp
  name: Spawn Point opfor Platoon Operations Officer
  components:
  - type: SpawnPoint
    job_id: AU14JobOpforPlatOp
  - type: Sprite
    state: syn_spawn

- type: startingGear
  id: AU14GearopforPlatOpDummy
  equipment:
    shoes: CMBootsBlack
    head: AU14JunglePatrolCap
    jumpsuit: CMJumpsuitXOFormal
    ears: AU14HeadsetSectionLeaderopfor
