- type: rank
  id: RMCRankMajorGeneral
  name: Major General
  prefix: MajGen.
  paygrade: O8

- type: rank
  id: RMCRankBrigadierGeneral
  name: Brigadier General
  prefix: BGen.
  paygrade: O7

- type: rank
  id: RMCRankColonel
  name: Colonel
  prefix: Col.
  paygrade: O6

- type: rank
  id: RMCRankLieutenantColonel
  name: Lieutenant Colonel
  prefix: LtCol.
  paygrade: O5

- type: rank
  id: RMCRankMajor
  name: Major
  prefix: Maj.
  paygrade: O4

- type: rank
  id: RMCRankCaptain
  name: Captain
  prefix: Capt.
  paygrade: O3

- type: rank
  id: RMCRankFirstLT
  name: First Lieutenant
  prefix: 1stLt.
  paygrade: O2

- type: rank
  id: RMCRankSecondLT
  name: Second Lieutenant
  prefix: 2ndLt.
  paygrade: O1

- type: rank
  id: RMCRankChiefWarrantOfficer5
  name: Chief Warrant Officer 5
  prefix: CWarOff5.
  paygrade: W5

- type: rank
  id: RMCRankChiefWarrantOfficer4
  name: Chief Warrant Officer 4
  prefix: CWarOff4.
  paygrade: W4

- type: rank
  id: RMCRankChiefWarrantOfficer3
  name: Chief Warrant Officer 3
  prefix: CWarOff3.
  paygrade: W3

- type: rank
  id: RMCRankChiefWarrantOfficer
  name: Chief Warrant Officer 2
  prefix:  CWarOff2.
  paygrade: W2

- type: rank
  id: RMCRankWarrantOfficer
  name: Warrant Officer
  prefix: WarOff.
  paygrade: W1
