# base
- type: randomHumanoidSettings
  id: RMCEventHumanoid
  components:
  - type: GhostTakeoverAvailable
  - type: RandomHumanoidAppearance
  - type: RandomHumanoidAppearanceWhitelisted
    allowedMaleHairStyles:
    - RMCHumanHairCrew
    - RMCHumanHairAviator
    - RMCHumanHairJensen
    - RMCHumanHairAverageJoe
    - AU14HumanHairCIA5
    - RMCHumanHairCombover
    - RMCHumanHairCombover2
    - RMCHumanHairCplDietrich
    - RMCHumanHairCut
    - RMCHumanHairHeadStubble
    - RMCHumanHairHighAndTight
    - RMCHumanHairHighfade
    - RMCHumanHairHighlight
    - AU14HumanHairIRS
    - RMCHumanHairLtRasczak
    - RMCHumanHairMarineFade
    - RMCHumanHairMarineFlatTop
    - RMCHumanHairMedfade
    - RMCHumanHairNofade
    - RMCHumanHairShavedpart
    - RMCHumanHairShavedHead
    - RMCHumanHairShort
    - RMCHumanHairSideUndercutHang
    - RMCHumanHairSkinhead
    - RMCHumanHairTaper
    - RMCHumanHairWardaddy
    - RMCHumanHairUndercut
    - RMCHumanHairUndercutTop
    allowedFemaleHairStyles:
    - RMCHumanHairShortbangs
    - RMCHumanHairBobcurl
    - RMCHumanHairMarineBun
    - RMCHumanHairBun
    - RMCHumanHairFringetail
    - AU14HumanHairLowBun
    - AU14HumanHairLowPonyTail
    - AU14HumanHairLowPonyTailAlt
    - RMCHumanHairPonytail1
    - RMCHumanHairPonytail7
    - RMCHumanHairPvtRedding
    - RMCHumanHairPvtVasquez
    - RMCHumanHairLong
    - RMCHumanHairPixieCutLeft
    - RMCHumanHairPixieCutRight
    allowedHairColorsHex:
    - "#0B0B0B"
    - "#1A1A1A"
    - "#222222"
    - "#2B1B0F"
    - "#3B2314"
    - "#4A2E1A"
    - "#5A3A22"
    - "#6B4A2F"
    - "#9C8651"
    - "#B79A5A"
    - "#4A1F12"
    - "#7A5E42"
    allowedEyeColorsHex: [ "#000000" ]
    beardChance: 0.1

- type: randomHumanoidSettings
  parent: RMCEventHumanoid
  id: RMCRandomHumanoidBase
  components:
  - type: GhostRolePreventCryoSleep
  - type: GhostRoleApplySpecial

# squads
- type: randomHumanoidSettings
  parent: RMCRandomHumanoidBase
  id: RMCAlphaBase
  components:
  - type: GhostRoleApplySpecial
    squad: SquadAlpha

- type: randomHumanoidSettings
  parent: RMCRandomHumanoidBase
  id: RMCBravoBase
  components:
  - type: GhostRoleApplySpecial
    squad: SquadBravo

- type: randomHumanoidSettings
  parent: RMCRandomHumanoidBase
  id: RMCCharlieBase
  components:
  - type: GhostRoleApplySpecial
    squad: SquadCharlie

- type: randomHumanoidSettings
  parent: RMCRandomHumanoidBase
  id: RMCDeltaBase
  components:
  - type: GhostRoleApplySpecial
    squad: SquadDelta

- type: randomHumanoidSettings
  parent: RMCRandomHumanoidBase
  id: RMCEchoBase
  components:
  - type: GhostRoleApplySpecial
    squad: SquadEcho

- type: randomHumanoidSettings
  parent: RMCRandomHumanoidBase
  id: RMCFoxtrotBase
  components:
  - type: GhostRoleApplySpecial
    squad: SquadFoxtrot

- type: randomHumanoidSettings
  parent: RMCRandomHumanoidBase
  id: RMCIntelBase
  components:
  - type: GhostRoleApplySpecial
    squad: SquadIntel

- type: randomHumanoidSettings
  parent: RMCRandomHumanoidBase
  id: RMCUnassignedBase
  components:
  - type: GhostRoleApplySpecial
