- type: entity
  id: SquadBase
  abstract: true
  components:
  - type: SquadTeam
    background:
      sprite: _RMC14/Interface/cm_job_icons.rsi
      state: hudsquad
    maxRoles:
      CMSquadLeader: 1
      CMFireteamLeader: 2
      CMWeaponsSpecialist: 1
      CMSmartGunOperator: 1
      CMCombatTech: 3
      CMHospitalCorpsman: 4

- type: entity
  parent: SquadBase
  id: SquadAlpha
  name: Alpha
  components:
  - type: SquadTeam
    roundStart: true
    color: "#E61919"
    radio: MarineAlpha
    accessLevels:
    - CMAccessAlpha
    minimapBackground:
     sprite: /Textures/_RMC14/Interface/map_blips.rsi
     state: background_alpha

- type: entity
  parent: SquadBase
  id: SquadBravo
  name: Bravo
  components:
  - type: SquadTeam
    roundStart: true
    color: "#FFC32D"
    radio: MarineBravo
    accessLevels:
    - CMAccessBravo
    minimapBackground:
     sprite: /Textures/_RMC14/Interface/map_blips.rsi
     state: background_bravo

- type: entity
  parent: SquadBase
  id: SquadCharlie
  name: Charlie
  components:
  - type: SquadTeam
    roundStart: true
    color: "#C864C8"
    radio: MarineCharlie
    accessLevels:
    - CMAccessCharlie
    minimapBackground:
     sprite: /Textures/_RMC14/Interface/map_blips.rsi
     state: background_charlie

- type: entity
  parent: SquadBase
  id: SquadDelta
  name: Delta
  components:
  - type: SquadTeam
    roundStart: true
    color: "#4148C8"
    radio: MarineDelta
    accessLevels:
    - CMAccessDelta
    minimapBackground:
     sprite: /Textures/_RMC14/Interface/map_blips.rsi
     state: background_delta

- type: entity
  parent: SquadBase
  id: SquadFoxtrot
  name: Foxtrot
  components:
  - type: SquadTeam
    color: "#C47A50"
    radio: MarineFoxtrot
    accessLevels:
    - CMAccessAlpha
    - CMAccessBravo
    - CMAccessCharlie
    - CMAccessDelta
    minimapBackground:
     sprite: /Textures/_RMC14/Interface/map_blips.rsi
     state: background_foxtrot
    canSupplyDrop: false

- type: entity
  parent: SquadBase
  id: SquadEcho
  name: Echo
  components:
  - type: SquadTeam
    color: "#67D692"
    radio: MarineEcho
    accessLevels:
    - CMAccessAlpha
    - CMAccessBravo
    - CMAccessCharlie
    - CMAccessDelta
    minimapBackground:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: background_echo

- type: entity
  parent: SquadBase
  id: SquadIntel
  name: Auxiliary
  components:
  - type: SquadTeam

    color: "#053818"
    blacklistedSquadArmor:
    - Helmet
    - Armor
    radio: MarineIntel
    minimapBackground:
     sprite: /Textures/_RMC14/Interface/map_blips.rsi
     state: background_intel
    canSupplyDrop: false
    maxRoles:
      CMCombatTech: 3
      CMHospitalCorpsman: 4
      CMSmartGunOperator: 1 # for astor
      CMWeaponsSpecialist: 1
      CMFireteamLeader: 1
      CMSquadLeader: 0
  - type: Tag
    tags:
    - RMCSquadIntel

- type: Tag
  id: RMCSquadIntel

- type: entity
  parent: SquadBase
  id: SquadPMC
  name: Corporate
  components:
  - type: SquadTeam
    color: "#FFAC1C"
    background:
      sprite: _RMC14/Interface/cm_job_icons.rsi
      state: empty
    blacklistedSquadArmor:
    - Helmet
    - Goggles
    - Armor
    - Gloves
    radio: WEYA
    minimapBackground:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: background_pmc
    canSupplyDrop: false
    group: WeYa
    leaderIcon:
      sprite: _RMC14/Interface/cm_job_icons.rsi
      state: weya_goon_lead
  - type: Tag
    tags:
    - SquadPMC

- type: Tag
  id: SquadPMC

- type: entity
  parent: SquadBase
  id: SquadFreelancer
  name: Freelancer
  components:
  - type: SquadTeam
    color: "#4559F5"
    background:
      sprite: _RMC14/Interface/cm_job_icons.rsi
      state: empty
    blacklistedSquadArmor:
    - Helmet
    - Goggles
    - Armor
    - Gloves
    radio: Colony
    minimapBackground:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: background_free
    canSupplyDrop: false
    group: Freelancer
    leaderIcon:
      sprite: _RMC14/Interface/cm_job_icons.rsi
      state: free_sl

- type: entity
  parent: SquadBase
  id: SquadRoyalMarines
  name: Royal Marines
  components:
  - type: SquadTeam
    color: "#3D6F43"
    background:
      sprite: _RMC14/Interface/cm_job_icons.rsi
      state: empty
    blacklistedSquadArmor:
    - Helmet
    - Goggles
    - Armor
    - Gloves
    radio: TSE
    minimapBackground:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: background_twe
    canSupplyDrop: false
    group: Royal Marines
    leaderIcon:
      sprite: _RMC14/Interface/cm_job_icons.rsi
      state: rmc_teamleader

- type: entity
  parent: SquadBase
  id: SquadProvost
  name: Provost
  components:
  - type: SquadTeam
    color: "#990218"
    background:
      sprite: _RMC14/Interface/cm_job_icons.rsi
      state: empty
    blacklistedSquadArmor:
    - Helmet
    - Goggles
    - Armor
    - Gloves
    radio: Provost
    minimapBackground:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: background_twe
    canSupplyDrop: false
    group: Provost
    leaderIcon:
      sprite: _RMC14/Interface/cm_job_icons.rsi
      state: hudsquad_pvl

- type: entity
  parent: SquadBase
  id: SquadFORECON
  name: Recon
  components:
  - type: SquadTeam
    color: "#32CD32"
    blacklistedSquadArmor:
    - Helmet
    - Goggles
    - Armor
    - Gloves
    radio: MarineAlpha
    minimapBackground:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: background_forecon
    canSupplyDrop: false
    group: FORECON
  - type: Tag
    tags:
    - RMCSquadFORECON

- type: Tag
  id: RMCSquadFORECON

- type: entity
  parent: SquadBase
  id: SquadSOF
  name: SOF
  components:
  - type: SquadTeam
    color: "#400000"
    background:
      sprite: _RMC14/Interface/cm_job_icons.rsi
      state: empty
    radio: MarineAlpha
    accessLevels: []
    minimapBackground:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: background_sof
    group: SOF
    leaderIcon:
      sprite: _RMC14/Interface/cm_job_icons.rsi
      state: hudsquad_soctl

- type: entity
  parent: SquadBase
  id: SquadCLF
  name: CLF
  components:
  - type: SquadTeam
    color: "#3aeb34"
    background:
      sprite: _RMC14/Interface/cm_job_icons.rsi
      state: empty
    blacklistedSquadArmor:
    - Helmet
    - Goggles
    - Armor
    - Gloves
    radio: Colony
    minimapBackground:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: background_spp
    canSupplyDrop: false
    group: CLF
    leaderIcon:
      sprite: _RMC14/Interface/cm_job_icons.rsi
      state: clf_sl

# --- OPFOR Squads ---
- type: entity
  parent: SquadBase
  id: SquadOpforIntel
  name: Auxiliary
  components:
  - type: SquadTeam
    roundStart: true
    color: "#1E90FF"
    group: OPFOR
    radio: OpforIntel
    accessLevels:
    - AU14AccessOpfor
    - AU14AccessGovfor
    minimapBackground:
     sprite: /Textures/_RMC14/Interface/map_blips.rsi
     state: background_intel

- type: entity
  parent: SquadBase
  id: SquadOpfor
  name: Sierra
  components:
  - type: SquadTeam
    color: "#bb91d8"
    radio: opfor
    group: OPFOR
    minimapBackground:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: background_sierra
    leaderIcon:
      sprite: _RMC14/Interface/cm_job_icons.rsi
      state: hudsquad_leader_a

- type: entity
  parent: SquadBase
  id: SquadOpforBravo
  name: Tango
  components:
  - type: SquadTeam
    roundStart: true
    color: "#c6c1a8"
    group: OPFOR
    radio: OpforBravo
    accessLevels:
    - AU14AccessOpfor
    - AU14AccessGovfor
    minimapBackground:
     sprite: /Textures/_RMC14/Interface/map_blips.rsi
     state: background_tango

- type: entity
  parent: SquadBase
  id: SquadOpforCharlie
  name:  Uniform
  components:
  - type: SquadTeam
    roundStart: true
    color: "#7A967E"
    radio: OpforCharlie
    group: OPFOR

    accessLevels:
    - AU14AccessOpfor
    - AU14AccessGovfor
    minimapBackground:
     sprite: /Textures/_RMC14/Interface/map_blips.rsi
     state: background_uniform

# --- GOVFOR Squads ---
- type: entity
  parent: SquadBase
  id: SquadGovforIntel
  name: Auxiliary
  components:
  - type: SquadTeam
    group: GOVFOR

    roundStart: true
    color: "#228B22"
    radio: GovforIntel
    accessLevels:
    - AU14AccessGovforSquad
    - AU14AccessOpfor
    minimapBackground:
     sprite: /Textures/_RMC14/Interface/map_blips.rsi
     state: background_intel

- type: entity
  parent: SquadBase
  id: SquadGovfor
  name: Alpha
  components:
  - type: SquadTeam
    color: "#F0433E"
    radio: MarineAlpha
    group: GOVFOR
    minimapBackground:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: background_alpha
    leaderIcon:
      sprite: _RMC14/Interface/cm_job_icons.rsi
      state: hudsquad_leader_a

- type: entity
  parent: SquadBase
  id: SquadGovforBravo
  name: Bravo
  components:
  - type: SquadTeam
    roundStart: true
    color: "#c7b646"
    group: GOVFOR
    radio: GovforBravo
    accessLevels:
    - AU14AccessGovforSquad
    - AU14AccessOpfor
    minimapBackground:
     sprite: /Textures/_RMC14/Interface/map_blips.rsi
     state: background_bravo

- type: entity
  parent: SquadBase
  id: SquadGovforCharlie
  name: Charlie
  components:
  - type: SquadTeam
    roundStart: true
    group: GOVFOR

    color: "#9D3EF0"
    radio: GovforCharlie
    accessLevels:
    - AU14AccessGovforSquad
    - AU14AccessOpfor
    minimapBackground:
     sprite: /Textures/_RMC14/Interface/map_blips.rsi
     state: background_charlie
