- type: department
  parent: CMDepartmentBase
  id: AU14DepartmentThreat
  name:  au-job-name-threat-member
  description: au14-department-threat-description
  color: "#e3ce94"
  roles:
  - AU14JobThreatLeader
  - AU14JobThreatMember
  departmentRadio: null
  headOfDepartment: null

- type: department
  parent: CMDepartmentBase
  id: AU14DepartmentThirdParty
  name: au14-department-third-party
  description: au14-department-third-party-description
  color: "#e3ce94"
  roles:
  - AU14JobThirdPartyLeader
  - AU14JobThirdPartyMember
  departmentRadio: null
  headOfDepartment: null

- type: department
  parent: CMDepartmentBase
  id: AU14DepartmentColonyMapSpecific
  name: au14-department-colony-mapspecific
  description: au14-department-colony-mapspecific-description
  color: "#e3ce94"
  roles:
  - AU14JobCivilianCMBDeputy
  - AU14JobCivilianCMBMarshal
  - AU14JobCivilianCWPSRanger
  - AU14JobCivilianPaPOfficer
  - AU14JobCiviliannspaConstable
  - AU14JobCivilianScientist
  - AU14JobCivilianUSASFRecruiter
  - AU14JobCivilianMiner
  - AU14JobCivilianPrisoner
  - AU14JobCivilianKellandWarden
  departmentRadio: null
  headOfDepartment: null

- type: department
  parent: CMDepartmentBase
  id: AU14DepartmentPrison
  name: au14-department-prison
  description: au14-department-prison-description
  color: "#e3ce94"
  roles:
  - AU14JobWYGuard
  departmentRadio: null
  headOfDepartment: null