- type: job
  parent: AU14JobPlatOpBase
  id: AU14JobGOVFORPlatOpUPP
  name: Staff Officer
  description: au14-job-description-govforplatop
  setPreference: false
  canBeAntag: false
  ranks:
    UPP_Lieutenant:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORPlatOp
      time: 216000 # 60 hours
    UPP_JuniorLieutenant: []
  startingGear: AU14GearGOVFORPlatOp
  dummyStartingGear: AU14GearGOVFORPlatOpDummy
  icon: "AU14JobIconOpsOfc"
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-govfor
  accessGroups:
  - AU14GovforCommand
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillCqc: 2
        RMCSkillConstruction: 2
        RMCSkillEndurance: 2
        RMCSkillEngineer: 2
        RMCSkillFirearms: 2
        RMCSkillFireman: 2
        RMCSkillIntel: 2
        RMCSkillJtac: 4
        RMCSkillLeadership: 3
        RMCSkillMedical: 3
        RMCSkillNavigations: 1
        RMCSkillOverwatch: 1
        RMCSkillPolice: 2
        RMCSkillPowerLoader: 2
        RMCSkillSurgery: 1
        RMCSkillVehicles: 1
    - type: JobPrefix
      prefix: au14-job-prefix-AU14JobGOVFORPlatOpUPP
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: synth
  hidden: true
