- type: job
  parent: CMJobBase
  id: AU14JobGOVFORDSPilotUPP
  name: Dropship Pilot
  description: au14-job-description-govfordspilot
  setPreference: false
  canBeAntag: false
  playTimeTracker: AU14JobGOVFORDSPilot
  ranks:
    UPP_Lieutenant:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORDSPilot
      time: 432000 # 120 hours
    UPP_JuniorLieutenant:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORDSPilot
      time: 216000 # 60 hours
    UPP_SeniorWarrantOfficer:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORDSPilot
      time: 108000 # 30 hours
    UPP_WarrantOfficer: []
  startingGear: AU14GearGOVFORDSPilot
  dummyStartingGear: AU14GearGOVFORDSPilotDummy
  icon: "AU14JobIconPilotOfficer"
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-govfor
  accessGroups:
  - AU14GovforPilot
  - AU14GovforCorpsman
  - AU14GovforSquad
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillFirearms: 2
        RMCSkillFireman: 1
        RMCSkillIntel: 1
        RMCSkillJtac: 2
        RMCSkillLeadership: 1
        RMCSkillMedical: 2
        RMCSkillOverwatch: 1
        RMCSkillPilot: 2
        RMCSkillPowerLoader: 2
        RMCSkillSurgery: 1
        RMCSkillPolice: 1
    - type: JobPrefix
      prefix: au14-job-prefix-AU14JobGOVFORDSPilotUPP
    - type: TacticalMapIcon
      icon:
        sprite: _RMC14/Interface/map_blips.rsi
        state: synth
  hidden: false