- type: job
  parent: AU14JobPlatoonCorpsmanBase
  id: AU14JobGOVFORPlatoonCorpsmanUPP
  name: Field Medic
  description: au14-job-description-govforplatooncorpsman
  setPreference: false
  ranks:
    UPP_StarschyRyadovoy:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORPlatoonCorpsman
      time: 1800 # 30 hours
    UPP_Yefreytor: []
  startingGear: AU14GearGOVFORPlatoonCorpsman
  dummyStartingGear: AU14GearGOVFORCorpsmanDummy
  icon: "AU14JobIconCorpsman"
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-govfor
  accessGroups:
  - AU14GovforCorpsman
  - AU14GovforSquad
  overwatchSortPriority: -2
  overwatchRoleName: Hospital Corpsmen
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillFirearms: 2
        RMCSkillFireman: 1
        RMCSkillJtac: 1
        RMCSkillMedical: 2
        RMCSkillSurgery: 1
        RMCSkillConstruction: 2
        RMCSkillEngineer: 3
        RMCSkillPolice: 1
    - type: JobPrefix
      prefix: au14-job-prefix-AU14JobGOVFORPlatoonCorpsmanUPP
    - type: TacticalMapIcon
      icon:
        sprite: _RMC14/Interface/map_blips.rsi
        state: synth
  hidden: true