- type: job
  parent: CMJobBase
  id: AU14JobGOVFORadvisorUPP
  name: au14-job-name-govforadvisor
  description: au14-job-description-govforadvisor
  setPreference: true
  canBeAntag: false
  playTimeTracker: AU14JobGOVFORadvisor
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 3600 # Set to 72000 once we are fully launched AU14 todo
  - !type:AgeRequirement
    requiredAge: 21
  - !type:TraitsRequirement
    inverted: true
    traits:
    - Epilepsy
  ranks:
    UPP_FirstSergeant:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORadvisor
      time: 432000 # 120 hours
    UPP_Chotar: []
  startingGear: AU14GearGOVFORadvisor
  dummyStartingGear: AU14GearGOVFORadvisorDummy
  icon: "AU14JobIconGovAdvisor"
  requireAdminNotify: true
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-govfor
  whitelisted: true
  accessGroups:
  - AU14GovforCommand
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - GOVFOR
    - type: Marine
      Faction: govfor
    - type: Skills
      preset: AU14SkillPresetPlatoonCommander
    - type: JobPrefix
      prefix: au14-job-prefix-govforadvisor
    - type: TacticalMapIcon
      icon:
        sprite: _RMC14/Interface/map_blips.rsi
        state: synth
  hidden: false
