- type: job
  parent: CMJobBase
  id: AU14JobGOVFORSquadAutomaticRiflemanUPP
  name: Machine Gunner
  description: au14-job-description-govforsquadautomaticrifleman
  setPreference: false
  playTimeTracker: AU14JobGOVFORSquadAutomaticRifleman
  ranks:
    UPP_Gefreiter:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadAutomaticRifleman
      time: 108000 # 30 hours
    UPP_Private: []
  startingGear: AU14GearGOVFORSquadAutomaticRifleman
  dummyStartingGear: AU14GearGOVFORAutoRiflemanDummy
  icon: "AU14JobIconAFN"
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-govfor
  accessGroups:
  - AU14GovforGunner
  overwatchSortPriority: -3
  overwatchShowName: true
  overwatchRoleName: Automatic Rifleman
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillFirearms: 2
        RMCSkillFireman: 1
        RMCSkillJtac: 1
        RMCSkillSmartGun: 1
        RMCSkillConstruction: 2
        RMCSkillEngineer: 3
        RMCSkillPolice: 1
    - type: SquadArmorWearer
    - type: JobPrefix
      prefix: au14-job-prefix-AU14JobGOVFORSquadAutomaticRiflemanUPP
    - type: TacticalMapIcon
      icon:
        sprite: _RMC14/Interface/map_blips.rsi
        state: smartgunner
  hidden: false