- type: job
  parent: CMJobBase
  id: AU14JobCivilianCorporateLiaison
  name: au14-job-name-civiliancorporateliaison
  description: au14-job-description-civiliancorporateliaison
  setPreference: true
  playTimeTracker: AU14JobCivilianCorporateLiaison
  ranks:
    RMCRankWeYaAssistantManager:
    - !type:RoleTimeRequirement
      role: AU14JobCivilianCorporateLiaison
      time: 900000 # 250 hours
    RMCRankWeYaExecutiveSupervisor:
    - !type:RoleTimeRequirement
      role: AU14JobCivilianCorporateLiaison
      time: 360000 # 100 hours
    RMCRankWeYaExecutiveSpecialist:
    - !type:RoleTimeRequirement
      role: AU14JobCivilianCorporateLiaison
      time: 180000 # 50 hours
    RMCRankWeYaSeniorExecutive:
    - !type:RoleTimeRequirement
      role: AU14JobCivilianCorporateLiaison
      time: 90000 # 25 hours
    RMCRankWeYaExecutive:
    - !type:RoleTimeRequirement
      role: AU14JobCivilianCorporateLiaison
      time: 36000 # 10 hours
    RMCRankWeYaJuniorExecutive: []
  startingGear: AU14GearCivilianCorporateLiaison
  icon: "CMJobIconLiaison"
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-colonycivilian
  accessGroups:
  - Colonist
  - auadmin
  - AUPrisonStaff
  - auwy
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillFireman: 1
        RMCSkillVehicles: 1
        RMCSkillDomestics: 1
        RMCSkillFirearms: 1
        RMCSkillIntel: 1
        RMCSkillOverwatch: 1
    - type: CMVendorUser
      id: AU14JobCivilianCorporateLiaison
      points: 70
    - type: JobPrefix
      prefix: au14-job-prefix-corporateliaison
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: synth
    - type: AssignSquad
      whitelist:
        tags:
        - SquadPMC
    - type: NpcFactionMember
      factions:
      - GOVFOR
    - type: Marine
      Faction: govfor
  hidden: false

- type: startingGear
  id: AU14GearCivilianCorporateLiaison
  equipment:
    jumpsuit: AU14CivilianWorkwearBlue
    shoes: RMCShoesLaceup
    id: AU14IDCardColonyCorporateLiaison
    outerClothing: AU14CivilianJacketOrangePufferJacket
    ears: RMCHeadsetDistressPMCPVE
    ears2: RMCM5CameraGear
  inhand:
  - RMCPortableVendorCorporate

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointCivilianCorporateLiaison
  name: Spawn Point Civilian Corporate Liaison
  components:
  - type: SpawnPoint
    job_id: AU14JobCivilianCorporateLiaison
  - type: Sprite
    state: syn_spawn

- type: playTimeTracker
  id: AU14JobCivilianCorporateLiaison
  isHumanoid: true
