- type: job
  parent: AU14JobPlatCoBase
  id: AU14JobGOVFORPlatCoRMC
  name: au14-job-name-govforplatcoRMC
  description: au14-job-description-govforplatco
  setPreference: true
  canBeAntag: false
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 18000 # 5 hours
  - !type:AgeRequirement
    requiredAge: 30
  - !type:TraitsRequirement
    inverted: true
    traits:
    - SocialAnxiety
    - SocialAnxietyHeavy
    - FrontalLisp
    - NonResuscitable
    - Epilepsy
  ranks:
    RMC_Captain:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORPlatCo
      time: 432000 # 120 hours
    RMC_Lieutenant: []
  startingGear: AU14GearGOVFORPlatCo
  dummyStartingGear: AU14GearGOVFORPlatCoDummy
  icon: "AU14JobIconPlatCo"
  requireAdminNotify: true
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-govforplatco
  accessGroups:
  - AU14GovforCommand
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: CommendationGiver
    - type: InnateCommandSpeech
    - type: NpcFactionMember
      factions:
      - GOVFOR
    - type: Marine
      Faction: govfor
    - type: Skills
      preset: AU14SkillPresetPlatoonCommander
    - type: JobPrefix
      prefix: au14-job-prefix-govforplatco
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: synth
  hidden: true
