- type: job
  parent: AU14JobSquadAutomaticRiflemanBase
  id: AU14JobGOVFORSquadAutomaticRiflemanRMC
  name: au14-job-name-govforsquadautomaticriflemanRMC
  description: au14-job-description-govforsquadautomaticrifleman
  setPreference: true
  requirements:
  - !type:TraitsRequirement
    inverted: true
    traits:
    - Epilepsy
    - NonResuscitable
  ranks:
    RMC_Corporal:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadAutomaticRifleman
      time: 108000 # 30 hours
    RMC_LanceCorporal:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadAutomaticRifleman
      time: 54000 # 15 hours
    RMC_Marine: []
  startingGear: AU14GearGOVFORSquadAutomaticRifleman
  dummyStartingGear: AU14GearGOVFORAutoRiflemanDummy
  icon: "AU14JobIconAFN"
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-govfor
  accessGroups:
  - AU14GovforGunner
  overwatchSortPriority: -3
  overwatchShowName: true
  overwatchRoleName: Automatic Rifleman
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - GOVFOR
    - type: Marine
      Faction: govfor
    - type: Skills
      preset: AU14SkillPresetPlatoonAutomaticRifleman
    - type: SquadArmorWearer
    - type: JobPrefix
      prefix: au14-job-prefix-govforsquadautomaticrifleman
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: smartgunner
  hidden: true
